config/routes.rb
Rails.application.routes.draw do
  resources :goods
  resources :boats

  root 'boats#index'
  post 'boats/getall' => 'boats#get_all'
  post 'boats/getboat' => 'boats#get_boat'
  post 'boats/getgoods' => 'boats#get_goods'

end

app/models/boat.rb
class Boat < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :goods, dependent: :destroy
end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :boat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
  end

  # GET /boats/1
  # GET /boats/1.json
  def show

  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_all
    boats = Boat.all
    boat_arr = []
    boats.each do |boat|
      hash = {
        :id => boat.id,
        :name => boat.name,
        :image => root_url + boat.image.to_s
      }
      boat_arr.push hash
    end
    render json: boat_arr
  end

  def get_boat
    if params.include?(:id)
      if Boat.exists?(:id => params[:id])
        boat = Boat.find_by(:id => params[:id])
        result = {
          :id => boat.id,
          :name => boat.name,
          :image => root_url + boat.image.to_s
        }
      else
        result = {:success => false, :message => 'Id does not exist'}
      end
    else
      result = {:success => false, :message => "Please check your paramaters !"}
    end
    render json: result
  end

  def get_goods
    if params.include?(:boat_id)
      if Boat.exists?(:id => params[:boat_id])
        result = Good.joins(:boat).where(boats: {id: [params[:boat_id]]})
      else
        result = {:success => false, :message => 'Id does not exist'}
      end
    else
      result = {:success => false, :message => 'Please check your paramaters'}
    end
    render json: result
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:name, :image)
    end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to @good, notice: 'Good was successfully created.' }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:name, :quantity, :boat_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/boats/_form.html.erb
<%= form_for(@boat) do |f| %>
  <% if @boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% @boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, multiple: false %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<h1>Editing Boat</h1>

<%= render 'form' %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.name %></td>
        <td><%= boat.image %></td>
        <td><%= link_to 'Show', boat %></td>
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boat', new_boat_path %>

app/views/boats/new.html.erb
<h1>New Boat</h1>

<%= render 'form' %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @boat.name %>
</p>

<p>
  <strong>Image:</strong>
  <img src= <%= @boat.image %> alt="Smiley face" height="200" width="200">
  <!-- <%= @boat.image %> -->
</p>

<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>

app/views/goods/_form.html.erb
<%= form_for(@good) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :boat_id %><br>
    <%= f.number_field :boat_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Editing Good</h1>

<%= render 'form' %>

<%= link_to 'Show', @good %> |
<%= link_to 'Back', goods_path %>

app/views/goods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Goods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Boat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.name %></td>
        <td><%= good.quantity %></td>
        <td><%= good.boat_id %></td>
        <td><%= link_to 'Show', good %></td>
        <td><%= link_to 'Edit', edit_good_path(good) %></td>
        <td><%= link_to 'Destroy', good, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Good', new_good_path %>

app/views/goods/new.html.erb
<h1>New Good</h1>

<%= render 'form' %>

<%= link_to 'Back', goods_path %>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @good.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @good.quantity %>
</p>

<p>
  <strong>Boat:</strong>
  <%= @good.boat_id %>
</p>

<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', goods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InterviewApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>